# Obtain more details about all versions of a specific Content View
---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    login: &login
      server_url: "{{ server_url}}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
  tasks:
  # Obtain information about a Content View and its versions
    - name: find all CVs
      redhat.satellite.resource_info:
        <<: *login
        organization: "Default Organization"
        resource: content_views
        search: 'name="{{ cv_name }}"'
      register: example_content

    - name: "find content view versions of {{ cv_name }}"
      redhat.satellite.resource_info:
        <<: *login
        organization: "Default Organization"
        resource: content_view_versions
        params:
          content_view_id: "{{ example_content.resources[0].id }}"
      register: version_information

    - name: Display content of version_information
      debug:
        var: version_information
        verbosity: 1

    - name: Initialize cv_version list
      set_fact:
        cv_version: []

    - name: Add versions to cv_version list
      set_fact:
        cv_version: "{{ cv_version + version_information.resources[0].version }}"
      loop: "{{ version_information.resources }}"

    - name: Display cv_version list
      debug:
        var: cv_version
        verbosity: 1

    - name: Delete older versions
      redhat.satellite.content_view_version:
        <<: *login
        organization: "Default Organization"
        content_view: "{{ cv_name }}"
        version: "{{ item.version }}"
        state: absent
      loop: "{{ version_information.resources }}"
      loop_control:
        index_var: version_index
      when: version_index < cv_version