---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    login: &login
      server_url: "{{ server_url}}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
  tasks:
  - name: "Show repositories"
    redhat.satellite.resource_info:
      <<: *login
      resource: "repositories"
    register: result

  - name: "Check if result is successful"
    debug:
      var: result.resources[0].last_sync.result

  - name: "Check if ended is less than 2 days"
    debug:
      var: result.resources[0].last_sync.ended_at