---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    login: &login
      server_url: "{{ server_url}}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
  tasks:
  - name: "Show repositories"
    redhat.satellite.resource_info:
      <<: *login
      resource: "repositories"
    register: result

  - debug:
      var: result.resources[0]