---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    login: &login
      server_url: "{{ server_url}}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
  tasks:
  - name: Display content of failed_repositories_dict_2
    debug:
      var: failed_repositories_dict_2
      verbosity: 1

  - name: "Sync repository"
    redhat.satellite.repository_sync:
      <<: *login
      repository: "{{ item.repo_name }}"
      product: "{{ item.product_name }}"
      organization: "Default Organization"
    with_dict: "{{ failed_repositories_dict_2 }}"